### ISSUE TITLE
[Feature]: UI

### ISSUE THREAD

**Issue by DeadReDeamed** [TI-2-2-A1-2122/picum#6]
### Details of Feature

Implementation of the UI that's going to be used in the app

### Style Guide

- [X] I agree to follow the Style Guide

**Comment by Jesse592** [comment]
![image](https://user-images.githubusercontent.com/74358041/145721581-13b20020-f179-4be2-ad3c-ea5026d1b74a.png)

Remider : Beter gebruiken we hiervoor een interfaceje, dit is een beetje vies
